## index fruits
GET http://localhost:3000/fruits.json


### create fruit
POST http://localhost:3000/fruits.json
content-type: application/json

{
  "name": "grapes",
  "color": "purple",
  "flavor": "rich and sweet, like the Concord grape, to the slightly spicy Black Beauty grape."
}

### show fruit
GET http://localhost:3000/fruits/5.json

### update fruit
PATCH http://localhost:3000/fruits/3.json
content-type: application/json

{
  "flavor": "melon, pineapple, candy and clove flavor notes"
}